name: banquillosl
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-81.0.dev <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  lottie: ^2.3.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/balonc_mock.jpg
   - assets/bask.jpg
   - assets/pista_vankillo.jpg
   - assets/userDefaultVankillo.PNG
   - assets/camisa_alineacion.png
   - assets/camisa_alineacion_adversario.png
   - assets/camisa_alineacion_adversario.jpg